{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=root variable=content_type}text/html{/set-block}
{set-block scope=root variable=subject}Ufficio Stampa della Provincia autonoma di Trento - Comunicati stampa{/set-block}
{set-block variable=$content}
<h1 style="font-size:38px;font-weight:bold;color:rgb(54,54,54);text-align:center;line-height:47px;letter-spacing:-1px;margin-bottom: 0">Le notizie selezionate per te</h1>
<h2 style="font-size:22px;color:rgb(148,148,148);text-align:center;font-weight:normal;line-height:30px;margin-top: 0">{currentdate()|l10n( 'date' )}</h2>

{foreach fetch(notification,digest_handlers,hash(date,$date.timestamp,address,$address)) as $handler}
{include handler=$handler date=$date address=$address uri=concat( "design:notification/handler/",$handler.id_string,"/view/digest_plain.tpl")}
{/foreach}

<p><small>
{"If you do not want to continue receiving these notifications,
change your settings at:"|i18n('design/standard/notification')}
https://{ezini("SiteSettings","SiteURL")}{concat("notification/settings/")|ezurl(no)}
</small></p>
{/set-block}
{include uri="design:social_mail_pagelayout.tpl" content=$content}